algorithm: srd
save_dir: ./saved_models/OSSL_cv/
save_name: srd_cifar100_and_places365_50000_resnet32x4_resnet8x4_1
resume: True
load_path: ./saved_models/OSSL_cv//srd_cifar100_and_places365_50000_resnet32x4_resnet8x4_1/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
use_aim: False
epoch: 200
num_train_iter: 204800
num_log_iter: 256
num_eval_iter: 2048
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 0
num_labels: 50000
uratio: 1
ema_m: 0.0
T: 1
gamma: 1
alpha: 1
beta: 1
criterion_kd_weight: 10
img_size: 32
crop_ratio: 0.875
optim: AdamW
lr: 0.0005
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net_teacher: resnet32x4
net_teacher_path: ./saved_models/OSSL_cv/fullysupervised_cifar100_and_places365_50000_resnet32x4_0/model_best.pth
net: resnet8x4
net_from_name: False
data_dir: ./data
dataset: cifar100_and_places365
train_sampler: RandomSampler
num_classes: 100
num_workers: 4
seed: 1
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10554
dist_backend: nccl
gpu: None
use_pretrain: False
