algorithm: supervised
save_dir: ./saved_models/OSSL_cv/
save_name: supervised_cifar100_and_places365_200_vgg13_2
resume: True
load_path: ./saved_models/OSSL_cv//supervised_cifar100_and_places365_200_vgg13_2/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
use_aim: False
epoch: 200
num_train_iter: 204800
num_log_iter: 256
num_eval_iter: 2048
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 0
num_labels: 200
uratio: 1
ema_m: 0.0
img_size: 32
crop_ratio: 0.875
optim: AdamW
lr: 0.0005
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: vgg13
net_from_name: False
data_dir: ./data
dataset: cifar100_and_places365
train_sampler: RandomSampler
num_classes: 100
num_workers: 4
seed: 2
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:13036
dist_backend: nccl
gpu: None
use_pretrain: False
