algorithm: dkd
save_dir: ./saved_models/OSSL_cv/
save_name: dkd_tiny_imagenet_100000_resnet50_resnet18_0
resume: True
load_path: ./saved_models/OSSL_cv//dkd_tiny_imagenet_100000_resnet50_resnet18_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
use_aim: False
epoch: 200
num_train_iter: 204800
num_log_iter: 256
num_eval_iter: 2048
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 0
num_labels: 100000
uratio: 1
ema_m: 0.0
T: 1
gamma: 1
alpha: 1
beta: 1
img_size: 32
crop_ratio: 0.875
optim: AdamW
lr: 0.0005
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net_teacher: resnet50
net_teacher_path: ./saved_models/OSSL_cv/fullysupervised_tiny_imagenet_100000_resnet50_0/model_best.pth
net: resnet18
net_from_name: False
data_dir: ./data
dataset: tiny_imagenet
train_sampler: RandomSampler
num_classes: 200
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10235
dist_backend: nccl
gpu: None
use_pretrain: False
